name: Setup Cangjie
description: 在 GitHub Actions 中安装仓颉
author: Zxilly
branding:
  icon: play
  color: blue
inputs:
  channel:
    description: 需要安装的仓颉版本通道，例如 lts, sts
    required: false
    default: lts
  version:
    description: 需要安装的仓颉版本，例如 0.53.13, 0.58.3，使用 latest 表示最新版，使用 auto 表明尝试从 cjpm.toml 中获取版本，如果没有则使用 latest
    required: false
    default: auto
  archive-path:
    description: 下载的 .zip/.tar.gz 文件的存储路径
    required: false
outputs:
  version:
    description: 安装的仓颉版本
runs:
  using: node24
  main: dist/index.js
