name: Test Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4

      - name: Build test
        run: |
          pnpm install
          pnpm run build
